version: "3.8"

volumes:
  traefik-data:
  mongodb:

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - ./app:/code/app
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_PASSWORD=${MONGO_ROOT_PASSWORD}


  mongo:
    image: mongo:7.0.3
    restart: unless-stopped
    #No port is exposed by default. Use mongo express at localhost:8081
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - mongodb:/data/db

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo

  webserver:
    build:
      context: ./
      dockerfile: Dockerfile-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./web/html:/usr/share/nginx/html
    depends_on:
      - server